---
title: "Publicações"
---

## Artigos

### 2025

::: {style="text-align: justify"}
Pauletti Filho, M.; **Santos Neto, E. A.**; Canizares, D. C. C.; Delabie, J. H. C. [Predatory ants of the genus *Leptogenys* Roger, 1861 (Formicidae, Ponerinae) from Bahia, Brazil, preserved in the 'Coleção do Laboratório de Mirmecologia do Centro de Pesquisas do Cacau'.](https://www.researchgate.net/publication/399428927_PREDATORY_ANTS_OF_THE_GENUS_Leptogenys_Roger_1861_FORMICIDAE_PONERINAE_FROM_BAHIA_BRAZIL_PRESERVED_IN_THE_COLECAO_DO_LABORATORIO_DE_MIRMECOLOGIA_DO_CENTRO_DE_PESQUISAS_DO_CACAU) Agrotrópica, v. 37, p. 33-48, 2025.
:::

### 2024

::: {style="text-align: justify"}
**Santos-Neto, E. A.**; Chaul, J. C. M.; Delabie, J. H. C. [New species and new records of *Strumigenys* Smith, 1860 (Formicidae: Myrmicinae) from the Neotropical *schulzi* species group.](https://www.mdpi.com/2673-6500/4/3/32) Taxonomy, v. 4, p. 633-648, 2024.
:::

### 2023

::: {style="text-align: justify"}
Bombi-Haedo, K.; **Santos-Neto, E. A.**; Maldonado, M. B. [Ficha zoológica *Strumigenys louisianae* Roger, 1863.](https://szu.org.uy/assets/noticias/noticias_szu_16_59.pdf) Boletín de la Sociedad Zoológica del Uruguay, v. 31, p. 25-27, 2023.

Pauletti Filho, M.; **Santos-Neto, E. A.**; Delabie, J. H. C. [Diversidade das formigas predadoras do gênero *Strumigenys* Smith, 1860 (Formicidae, Myrmicinae) nas áreas experimentais do Centro de Pesquisa do Cacau, CEPLAC, em Ilhéus, Bahia.](https://www.researchgate.net/publication/378004779_DIVERSIDADE_DAS_FORMIGAS_PREDADORAS_DO_GENERO_Strumigenys_Smith_1860_FORMICIDAE_MYRMICINAE_NAS_AREAS_EXPERIMENTAIS_DO_CENTRO_DE_PESQUISA_DO_CACAU_CEPLAC_EM_ILHEUS_BAHIA) Agrotrópica, v. 35, p. 173-176, 2023.

**Santos-Neto, E. A.**; Koch, E. B. A.; Arnhold, A.; Delabie, J. H. C. First records of the exotic ant *Strumigenys rogeri* Emery, 1890 in Brazil. Sociobiology, v. 70, p. e9886, 2023.
:::

### 2022

::: {style="text-align: justify"}
Silva, R. R.; Martello, F.; Feitosa, R. M.; Silva, O. G. M.; Prado, L. P.; Brandão, C. R. F.; Albuquerque, E. Z.; Morini, M. S. C.; Delabie, J. H. C.; \[...\] **Santos Neto, E. A.**; et al. Atlantic ants: a data set of ants in Atlantic Forests of South America. Ecology, v. 103, p. e03580, 2022.

Arnhold, A.; Koch, E. B. A.; Nunes, L. O.; Silva, P. S.; **Santos-Neto, E. A.**; Delabie, J. H. C.; Mariano, C. S. F. Uso da armadilha de tipo Malaise omnidirecional no monitoramento de insetos num agrossistema cacaueiro. Agrotrópica, v. 34, p. 189-199, 2022.
:::

### 2020

::: {style="text-align: justify"}
Koch, E. B. A.; Marques, T. E. D.; Mariano, C. S. F.; **Santos-Neto, E. A.**; Arnhold, A.; Peronti, A. L. B. G.; Delabie, J. H. C. Diversidade e preferências estruturais para o mutualismo entre formigas e hemípteros em cacaueiros (*Theobroma cacao* L., Sterculiaceae). Boletim do Museu Paraense Emílio Goeldi — Ciências Naturais, v. 15, n. 1, p. 65-81, 2020.

Delabie, J. H. C.; **Santos-Neto, E. A.**; Oliveira, M. L.; Silva, P. S.; Santos, R. J.; Caitano, B.; Mariano, C. S. F.; Arnhold, A.; Koch, E. B. A. A coleção de Formicidae do Centro de Pesquisas do Cacau (CPDC), Ilhéus, Bahia, Brasil. Boletim do Museu Paraense Emílio Goeldi — Ciências Naturais, v. 15, p. 289-305, 2020.
:::

## Capítulos de livros publicados

### 2025

::: {style="text-align: justify"}
Ulysséa, M. A.; Azevedo-Silva, M.; Rosumek, F. B.; Jacintho, G. F.; **Santos-Neto, E. A.**; Lima, H. P.; Souza, I. N.; Lima, R. L. C. Unveiling the lives of ants: a call to observe their fascinating natural world. In: Feitosa, R. M.; Ribas, C. R.; Schmidt, F. A. (Eds.). *Brazilian Myrmecology: Exploring the World's Richest Ant Fauna*. 1. ed. Científica Digital, Barueri, 2025. v. 1, p. 100-122.

Schmidt, F. A.; Costa, M. M. S.; Fontenele, L. K.; Dutra, D. B. S.; Silva, O. G. M.; Nagatani, V. H.; **Santos-Neto, E. A.**; Feitosa, R. M. Western frontier in Brazilian ant diversity: contribution of Rede BIA to ant diversity know in Southwestern Amazon. In: Feitosa, R. M.; Ribas, C. R.; Schmidt, F. A. (Eds.). *Brazilian Myrmecology: Exploring the World's Richest Ant Fauna*. 1. ed. Científica Digital, Barueri, 2025. p. 465-478.
:::

### 2019

::: {style="text-align: justify"}
Fraga, C. N.; Peixoto, A. L.; Leite, Y. L. R.; Santos, N. D.; Oliveira, J. R. P. M.; \[...\] **Santos-Neto, E. A.** Lista da fauna e flora ameaçadas de extinção no estado do Espírito Santo. In: Fraga, C. N.; Formigoni, M. H.; Chaves, F. G. (Eds.). *Lista da Fauna e Flora Ameaçadas de Extinção no Estado do Espírito Santo*. 1. ed. Instituto Nacional da Mata Atlântica, Santa Teresa, 2019. v. 1, p. 342-419.
:::
